### Venue
POST http://localhost:8080/venues
Content-Type: application/json

{
  "name": "실버스톤",
  "capacity": 2,
  "venuesType": "FIXED-SEAT",
  "possibleTimes": "10:00-20:00",
  "seats": [
    {
      "seatNumber": "A1",
      "seatType": "VIP"
    },
    {
      "seatNumber": "B1",
      "seatType": "일반"
    }
  ]
}
